version: "3"
services:
  postgres:
    image: postgres:15.3
    user: postgres
    command: -c jit=off
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: dev-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 20
    volumes:
      - next-boss-example-postgres:/var/lib/postgresql/data

volumes:
  next-boss-example-postgres:
